blank_issues_enabled: false
contact_links:
  - name: Create issue in the Winglang Repository
    url: https://github.com/winglang/wing/issues/new
    about: We manage all issues in the Winglang repository for the time being :heart:
